### ISSUE TITLE
Missing LOGO for integration

### ISSUE THREAD

**Issue by sagitt** [LaggAt/hacs-govee#1]
Hi, good work! i'm using it :)
anyway you missing icon for integration:

![Schermata 2020-11-14 alle 14 47 37](https://user-images.githubusercontent.com/169086/99148527-66fa0080-2688-11eb-97c8-f3d90e21629d.png)

you can see how add it here: https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/
i make a simple logo for it, you can use it: 

**DOWNLOAD FILES HERE:** [LOGOS.zip](https://github.com/LaggAt/hacs-govee/files/5540830/LOGOS.zip)

![logo white background](https://user-images.githubusercontent.com/169086/99148725-c0166400-2689-11eb-83d5-ab076042d8a2.png)

**Comment by LaggAt** [comment]
Hi, thanks.

there is already a pull request:
https://github.com/home-assistant/brands/pull/1875

As the integration moved away from getting integrated in Home Assistant and rather provide an agile HACS repository I think I need to re-submit the PR to the custom folder again.

I'll keep this open to keep this in focus.

**Comment by sagitt** [comment]
> Hi, thanks.
> 
> there is already a pull request:
> [home-assistant/brands#1875](https://github.com/home-assistant/brands/pull/1875)
> 
> As the integration moved away from getting integrated in Home Assistant and rather provide an agile HACS repository I think I need to re-submit the PR to the custom folder again.
> 
> I'll keep this open to keep this in focus.

well, anyway if you want i can translate it to italian language

i have another 2 problems:
1) why sometime the led strip power change from on/off toggle to 2 flash for on \ off?
3) white temperature slide not work

i have H6159

**Comment by LaggAt** [comment]
Please keep the issues separated. Just quick answers here: 1. when the state is calculated locally, and not from api (just after switching e.g.) this is expected behavour. When the next state arrives from api the stateful button re-appears. 2. works for my device, please post a new issue containing debug logs.

***Let's keep this the "missing logo" issue***

Regarding the logo PR there are some prequisites we need to go to first: https://hacs.xyz/docs/publish/include
This may take some time, I'll close here when all PR's are submitted and we can just wait.

**Comment by sagitt** [comment]
> Please keep the issues separated. Just quick answers here: 1. when the state is calculated locally, and not from api (just after switching e.g.) this is expected behavour. When the next state arrives from api the stateful button re-appears. 2. works for my device, please post a new issue containing debug logs.
> 
> _**Let's keep this the "missing logo" issue**_
> 
> Regarding the logo PR there are some prequisites we need to go to first: https://hacs.xyz/docs/publish/include
> This may take some time, I'll close here when all PR's are submitted and we can just wait.

just opened

**Comment by Curtisjk** [comment]
I have submitted PRs for custom component logo (instead of core component) here https://github.com/home-assistant/brands/pull/2374 and wheels-custom-integrations https://github.com/home-assistant/wheels-custom-integrations/pull/349

**Comment by Curtisjk** [comment]
Merged into https://github.com/home-assistant/brands/ and should now show in HA Frontend. 

This issue can be closed now @LaggAt

**Comment by LaggAt** [comment]
Thanks a lot, finally!
