### ISSUE TITLE
LAN Control from different subnet.

### ISSUE THREAD

**Issue by dominikremes** [LaggAt/hacs-govee#103]
I like to keep my IoT devices separated on a different VLAN than my main devices (PCs, phones, servers). For now it seems like the lan based api can't connect to the govee light strip if it is in a separated network (of course I've permitted every communication between the light strip and HA). Is it possible to solve this issue? (For example by pointing HomeAssistan to the IP of the light strip).

**Comment by williamokano-dh** [comment]
If the IP is from a different subnet than the issue is not from the hacs, but rather how PC networking works.

They are in different networks, they can't reach each other. Your must have some kind of lan peering or having all the stuff you need on the same subnet.

**Comment by dominikremes** [comment]
> If the IP is from a different subnet than the issue is not from the integration, but rather how PC networking works.
> 
> They are in different networks, they can't reach each other. Your must have some kind of lan peering or having all the stuff you need on the same subnet.

Nevermind, I've probably figured it out. I'm gonna try it when I have some time.

Btw. Never tell a network engineer, that the issue is "how PC networking works", cause it's not. Multicast can be routed 🙃.  And maybe you just missunderstood me, but the sentence "they can't reach each other" is not true. As I said, the traffic between them is permitted and they totally CAN communicate. I just need to make multicast work properly on the router

**Comment by williamokano-dh** [comment]
You're right, I was just trying to simplify the reply

**Comment by flippedcracker** [comment]
> Btw. Never tell a network engineer, that the issue is "how PC networking works", cause it's not. Multicast can be routed 🙃. And maybe you just missunderstood me, but the sentence "they can't reach each other" is not true. As I said, the traffic between them is permitted and they totally CAN communicate. I just need to make multicast work properly on the router

And everyone is just supposed to _know_ you're a network engineer 🙃
