### ISSUE TITLE
Dependency conflict with core `nam`, `gios` and `brother` integrations

### ISSUE THREAD

**Issue by bieniu** [LaggAt/hacs-govee#108]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
The core `nam`, `gios` and `brother` integrations use backend libraries which use `dacite>=1.7.0` package.  Govee integration causes dependency conflict because it forces `dacite` version `1.6.0` to be installed.

## Debug log

```text

Add your logs here.

```

**Comment by pejotigrek** [comment]
+1 from me - had some problems with core `nam` integration too.
after forceing `govee` to install `dacite` 1.7.0 everything works smoothly, so it would be nice to have it "out of the box" :)

**Comment by KitHubek** [comment]
the same here

**Comment by lazyjai** [comment]
+1 conflicts with Roborock as well. Update Govee to the newest dacite would be ideal.

**Comment by GitMeTender** [comment]
+1 please fix :)

**Comment by GitMeTender** [comment]
> +1 from me - had some problems with core `nam` integration too.
> after forceing `govee` to install `dacite` 1.7.0 everything works smoothly, so it would be nice to have it "out of the box" :)

could you please make a short tut for this? would help a lot of people! 💯

**Comment by sugarfunk** [comment]
> > +1 from me - had some problems with core `nam` integration too.
> > after forceing `govee` to install `dacite` 1.7.0 everything works smoothly, so it would be nice to have it "out of the box" :)
> 
> could you please make a short tut for this? would help a lot of people! 💯

1) Change the dependency in the manifest
![image](https://github.com/LaggAt/hacs-govee/assets/1361962/e136c064-f694-4514-9e5b-4f1fbabc64e4)

2) Reload the integration
![image](https://github.com/LaggAt/hacs-govee/assets/1361962/e95b7c5f-eba5-46e3-a23c-8d430c894209)

3) Reboot/restart

**Comment by DataBitz** [comment]
> +1 conflicts with Roborock as well. Update Govee to the newest dacite would be ideal.

I could not use the HA core Roborock integration for months and finally found Govee was the cause.
Had to switch to the govee2mqtt addon and remove this addon because of it.
