### ISSUE TITLE
Error setting up entry govee for govee

### ISSUE THREAD

**Issue by KitHubek** [LaggAt/hacs-govee#109]
HA ver.

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Interface: 20230309.1 - latest

## Version of the custom_component

0.2.2

## Configuration

```yaml

Logger: homeassistant.config_entries
Source: custom_components/govee/__init__.py:67
Integration: Govee ([documentation](https://github.com/LaggAt/hacs-govee/blob/master/README.md), [issues](https://github.com/LaggAt/hacs-govee/issues))
First occurred: 21:20:28 (1 occurrences)
Last logged: 21:20:28

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'
```

## Describe the bug
integration not load at start and cant load via manual, summarry: not working

## Debug log

```text

Add your logs here.

```

**Comment by vdubey11** [comment]
Seeing the same error for this integration in my home assistant as well

Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

```
 Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'
```

**Comment by GuidoTraversari** [comment]
I have the same errors... Have u solve It?

Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/govee/__init__.py:67
Integration: Govee (documentation, issues)
First occurred: 23:17:07 (1 occurrences)
Last logged: 23:17:07

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'

**Comment by GuidoTraversari** [comment]
Up

**Comment by zockol** [comment]
up

**Comment by carlos-algms** [comment]
Same here 😞

**Comment by peluho** [comment]
Same error over here, started today.

'''
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/govee/__init__.py:67
Integration: Govee (documentation, issues)
First occurred: 10:02:00 PM (1 occurrences)
Last logged: 10:02:00 PM

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'
'''

**Comment by CapricornDog** [comment]
Same here but only started today.

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/govee/__init__.py:67
Integration: Govee (documentation, issues)
First occurred: 0:44:32 am (1 occurrences)
Last logged: 0:44:32 am

Error setting up entry govee for govee
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/govee/__init__.py", line 67, in async_setup_entry
    await hub.rate_limit_delay()
AttributeError: 'Govee' object has no attribute 'rate_limit_delay'

**Comment by accordxtc** [comment]
Add me to the list. Completely broken. Tried new API key and to re add Govee integration and it now errors and says:

Cannot connect. Is the API-Key correct and the internet connection working?

**Comment by andredp** [comment]
Same as @accordxtc

**Comment by palmerpesta1** [comment]
Had the same issue. Redownloaded in HACs and it worked again.

**Comment by accordxtc** [comment]
@palmerpesta1 just redownloaded as well and it works. Not sure what cause all that but thanks for sharing a quick fix.

**Comment by hightime81** [comment]
> @palmerpesta1 just redownloaded as well and it works. Not sure what cause all that but thanks for sharing a quick fix.

could you share how to re-download? would i have to delete it (and all my entities) to do so?

**Comment by GuidoTraversari** [comment]
Yes I confirm, just delete the integration and re-install it.. after reinstalling it if it doesn't give error it works.. if it gives error wait about 24 hours and then it works again (even without mandatory reinstall).
It always seems to be the goove limited api calls thing... this causes the component to crash creating the error... For now there is little to do but wait for goove to fix!

**Comment by KitHubek** [comment]
for me change poll interval to 60 solved problem. I have 2 govee devices. If someone has more devices, this value i think should be increased to a larger value depending on how many devices You have

**Comment by yebo29** [comment]
> for me change poll interval to 60 solved problem. I have 2 govee devices. If someone has more devices, this value i think should be increased to a larger value depending on how many devices You have
> 
> ![Adnotacja 2023-05-06 101155](https://user-images.githubusercontent.com/91805313/236612180-4723b1ff-83c7-4d20-997c-6cb58a695d6e.jpg)

Trying this now. Thanks for the tip. Hopefully it resolves this issue on my system. Thanks!
