### ISSUE TITLE
Can not add repo

### ISSUE THREAD

**Issue by boostedgti916** [LaggAt/hacs-govee#11]
I am getting the following error any help? 

21-01-05 21:52:15 ERROR (MainThread) [supervisor.store] https://github.com/LaggAt/hacs-govee is not a valid add-on repository
21-01-05 21:52:15 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/217cf69b/repository.json: [Errno 2] No such file or directory: '/data/addons/git/217cf69b/repository.json'

**Comment by Kosh42** [comment]
Same issue here. Though I'm trying to add this first time and get `Invalid Add-on repository!`.

**Comment by boostedgti916** [comment]
I found out that you have to install HACS then add the repo from there.

**Comment by Kosh42** [comment]
I was being a numpty. Adds the repo fine.

**Comment by boostedgti916** [comment]
> I was being a numpty. Adds the repo fine.

Yup

**Comment by LaggAt** [comment]
yes, it's a hacs repo. Glad you figured that.
