### ISSUE TITLE
Missing govee_learning.yaml

### ISSUE THREAD

**Issue by Sleeepy2** [LaggAt/hacs-govee#13]
I keep getting the below error in my log. 
Setup through HACS with no issues and everything works fine.
I have a H6104 but will be replacing it with a H6199 (probably today).

I do not have the govee_learning.yaml in config folder, it's also not in the custom_compoents folder either.

Logger: custom_components.govee.learning_storage
Source: custom_components/govee/learning_storage.py:40
Integration: Govee LED strips (documentation, issues)
First occurred: 9:07:02 (1 occurrences)
Last logged: 9:07:02

There is no /config/govee_learning.yaml file containing learned information about your devices. This is normal for first start of Govee integration.

**Comment by LaggAt** [comment]
Hi, never had that issue again. 
Is your home assistant installation able to persist to the /config folder? Could be a permission issue.

If this doesn't help enable debug logging: see first post here: https://community.home-assistant.io/t/govee-led-strips-integration/228516
Try to set e.g. brightness to a high level after restart, it should try to create that file than.

If you still have issues feel free to re-open with some logs and more information.
