### ISSUE TITLE
Integration extremely slow

### ISSUE THREAD

**Issue by juliusjac** [LaggAt/hacs-govee#131]
Hi there,

the last days I was struggling with the "check the Internet connection problem". Now this issue seems to be solved but the Integration is extremely laggy. It takes up to 20 seconds for the devices to respond. Sometimes there is no response at all.

Is there any solution?

**Comment by szympulka** [comment]
I don't think this is an integration problem. Goove uses the http protocol for communication, and it is very slow. I'm surprised why they used it

**Comment by juliusjac** [comment]
Thanks for the reply.
After dealing a bit with the problem, I can absolutely agree to your comment.
I „fixed“ the problem by creating a homebridge service on my NAS. The Govee homebridge integration works without any problems. I integrated the Homebridge to my HomeKit service in Home assistant. This works fine for me, but I think it’s not the best solution.

**Comment by szympulka** [comment]
Can you share how you did it? Integration with goove is very poor :(

**Comment by szympulka** [comment]
I already understand. The problem is that the integration has no "wait time". Therefore, any change, even the smallest one, is sending a dozen requests to the server

**Comment by juliusjac** [comment]
@szympulka 
First you need a Homebridge Setup. Homebridge is I would say the beginner Homeassistant. For me it was easy to set up because I have a Synology NAS running. Here is a setup guide for Homebridge: https://homebridge.io/how-to-install-homebridge
Once you're done you need to install the Govee Integration for Homebridge: https://github.com/bwp91/homebridge-govee#readme
You will see this plugin is way more handsome than the HomeAssistant plugin. After setting everything in the plugin, you can control the lights via Homebridge. 
From now on you can add them directly to your HomeKit by using the Homebridge paring code. Second way is to integrate the Homebridge paring code to your HomeAssistant HomeKit service, than you can also control the hover lights via HomeAssist. If you set up scenes, automations etc. in HomeAssistant, I recommend the second way.
