### ISSUE TITLE
Implementation of Product: H713C

### ISSUE THREAD

**Issue by DavidRosseljong** [LaggAt/hacs-govee#136]
Hi,

I recently bought two H713C Heaters. Didn't find anything related to it and I don't have them in HA.

If I can help you in any way, please let me know.

Thanks.

**Comment by zigzagph** [comment]
Unfortunately the H713C model is currently not supported according to the Govee developer documentation. See link below.

[Govee supported devices](https://govee.readme.io/reference/govee-developer-api)

**Comment by DavidRosseljong** [comment]
Oh dang. Thanks for the information. Hopefully they change that in the near future. :)
