### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'goove'

### ISSUE THREAD

**Issue by woodmj74** [LaggAt/hacs-govee#14]
On 2021.03:

```
2021-03-04 20:34:36 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'govee'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'govee'
```

https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes outlines the information as for why

## Version of the custom_component

v0.1.5

## Describe the bug

HA v2021.3 has introduced rqt for version key in the manifest file.

**Comment by GlennGoddard** [comment]
Just to note this takes effect in June.  The 2021.4 version of HA adds this information.

No 'version' key in the manifest file for custom integration 'govee'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'govee'

**Comment by LaggAt** [comment]
Thanks, Merged.
I had this in one of my test branches for ble, and missed to push it :)
