### ISSUE TITLE
Please update Dacite

### ISSUE THREAD

**Issue by poiromaniax** [LaggAt/hacs-govee#159]
This integrations version of dacite interferes with setting up the core and HACS Roborock addon.

Please update it

**Comment by azimmerm** [comment]
Having the same issue here

**Comment by IneedAnewNick** [comment]
Also having the same issues I have disabled this integration because of this bit frustrating as it mean I have to leave the lights on all the time

**Comment by marcolivierarsenault** [comment]
I think I found a workaround, 
go download the `main/master` version of the integration. 

Here is an example for another repo. 
https://moonraker-home-assistant.readthedocs.io/en/stable/support/latest.html

**Comment by poiromaniax** [comment]
My workaround was to totally remove the HACS govee integration, restart HA. Setup Roborock and then reinstall this integration. Seems to work for now

**Comment by cbp0616** [comment]
Dacite needs to be updated.  This integration is actively interfering with others because of this.  Going to disable and shelve it.

**Comment by poiromaniax** [comment]
@LaggAt are you able to update dacite please?

Or is there someone here with knowledge that can fork and maintain this repo?

**Comment by IneedAnewNick** [comment]
All the fixes posted on this still didnt work for me I found myself having to disable it then restart so in my case my roborock could load and then re-enable the govee. 
Gets a little tiresome after a while so I installed spook custom integration that allows me to create an automation to disable govee before a restart and then re-enable it once I HA is running again.  Not perfect but as I say simply editing files to update the dacite number etc didnt work for me and the only other option is permanently disabling the govee addon

**Comment by IneedAnewNick** [comment]
> @IneedAnewNick can you post the automation yaml that uses spook to do that? I'd be interested in using that
`- id: '1710604253742'
  alias: Disable govee
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  condition: []
  action:
  - service: homeassistant.disable_config_entry
    metadata: {}
    data:
      config_entry_id: b2d386740f2be9da5505da8b1dfd1f5e
  mode: single
- id: '1710604584171'
  alias: Enable Govee after restart
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: homeassistant.enable_config_entry
    metadata: {}
    data:
      config_entry_id: b2d386740f2be9da5505da8b1dfd1f5e
  mode: single`

No idea if there is a better way and dont really care as it works :)

**Comment by poiromaniax** [comment]
> > @IneedAnewNick can you post the automation yaml that uses spook to do that? I'd be interested in using that
> > `- id: '1710604253742'
> > alias: Disable govee
> > description: ''
> > trigger:
> 
> * platform: homeassistant
>   event: shutdown
>   condition: []
>   action:
> * service: homeassistant.disable_config_entry
>   metadata: {}
>   data:
>   config_entry_id: b2d386740f2be9da5505da8b1dfd1f5e
>   mode: single
> * id: '1710604584171'
>   alias: Enable Govee after restart
>   description: ''
>   trigger:
>   
>   * platform: homeassistant
>     event: start
>     condition: []
>     action:
>   * delay:
>     hours: 0
>     minutes: 2
>     seconds: 0
>     milliseconds: 0
>   * service: homeassistant.enable_config_entry
>     metadata: {}
>     data:
>     config_entry_id: b2d386740f2be9da5505da8b1dfd1f5e
>     mode: single`
> 
> No idea if there is a better way and dont really care as it works :)

Thanks!

**Comment by DataBitz** [comment]
I could not use the HA core Roborock integration for months and finally found Govee was the cause.
Had to switch to the govee2mqtt addon and remove this addon because of it.

**Comment by ruudvanstrijp** [comment]
I see this govee integration hasn't been updated for half a year now. I'm having the same issue, causing my Roborock integration to fail. Should we just migrate to govee2mqtt instead or will this hacs-govee integration be updated?

**Comment by poiromaniax** [comment]
@ruudvanstrijp I migrated to govee2mqtt.
Setup was simple, works fantastic - I would definitely recommend it
