### ISSUE TITLE
Light state turn off  after 10s 

### ISSUE THREAD

**Issue by jason2021-de** [LaggAt/hacs-govee#21]
After turn on the Light @Home Assistant Light turn off after 10s Refresh-Rate  (H6159 / H6163) 

Also the brightness is still 40%.....

https://user-images.githubusercontent.com/76902841/115114460-d48bbf00-9f8f-11eb-8971-50868eed9de1.mp4

**Comment by Codexaudio** [comment]
Same issue, turn on led strip, led stip turns on, after 5s ha entity turns off (looks like fails to get state), led strip stays on.

**Comment by LaggAt** [comment]
Hi, please head over to the support thread here. This is an issue in the Govee API, but we made a workaround possible until they fixed it.

It's described here in detail:

https://community.home-assistant.io/t/govee-integration/228516/454?u=laggat
