### ISSUE TITLE
Support for Govee LED strip "DIY" scenes and other modes?

### ISSUE THREAD

**Issue by jgrn307** [LaggAt/hacs-govee#23]
**Is your feature request related to a problem? Please describe.**
I'd like to apply Govee DIY scenes I've either saved or created or initiate various modes via Home Assistant -- is there any possibility this could be added to the integration?  Does the API give you access to scenes and modes?  Or just single, full-strip color adjustments?

**Describe the solution you'd like**
Trigger a GOVEE DIY or other mode via HomeAssistant.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fpetru104** [comment]
I would like to see that too...

**Comment by LaggAt** [comment]
We all want :)

As this isn't possible to have with the Govee API only, we need to do #17 first.
So for now, I maked this as wontfix, because we will not be there that fast.

Be sure I keep that in mind once BLE works.

**Comment by clod986** [comment]
Adding to this because of #38 brought it up.

The WIFI bulb H6003 RGBWW does not have BLE, therefore I believe we could _try_ to set the scene also via WIFI.

**Comment by LaggAt** [comment]
Well, if that is possible we would need documentation :)
Could you ask Govee how it could be accomplished?

**Comment by clod986** [comment]
I sent them an email; let's see if I've managed to trigger an API documentation update 🤞

**Comment by descha000** [comment]
Any update on this since last year?

**Comment by jnbp** [comment]
I found a way how it is possible to trigger govee DIY scenes via homeassistant. It works smoothly, however you need to set up a few things.
The workaround is this great home bridge plugin for govee devices: https://github.com/bwp91/homebridge-govee
So I ended up to run in my homeassistant instance a portainer instance with a home bridge container, setup the lights, including the scenes (there are great instructions how to do it) and then include the home bridge devices back into homeassistant.

Works awesome and cool bonus it that also govee water leak sensors are working now.
