### ISSUE TITLE
H6154 Not Found

### ISSUE THREAD

**Issue by Neekster** [LaggAt/hacs-govee#28]
The Govee H6154 does not connect to HomeAssistant through this integration. It is supported by the API.

https://www.amazon.com/Govee-Assistant-Control-Lighting-Changing/dp/B08QJC1HKX/

**Comment by LaggAt** [comment]
Hi, is it connected to the WIFI and able to reach internet, or could you reconnect it using Govee Home app?
Usually this is the issue when a device isn't found.

If this isn't the issue, please provide debug logs as described here:
https://community.home-assistant.io/t/govee-integration/228516

**Comment by Neekster** [comment]
In the time since I wrote that issue, it appeared. I don't know why it
wasn't working earlier, but it is now.

**Comment by LaggAt** [comment]
Glad it worked.
