### ISSUE TITLE
Document installation without HACS

### ISSUE THREAD

**Issue by tibbon** [LaggAt/hacs-govee#30]
I'm running HA in Kubernetes, and the standard image doesn't come with `aiogithubapi queueman`, which makes installing HACS a pain. Is there any way to install this without HACS to my /config directory?

**Comment by LaggAt** [comment]
For every custom component, you may just copy the directory unter custom_components folder to your custom_components folder (which you may have to create)

e.g. in your config dir:
./custom_components/govee/

you may take this from the release zip or tar.gz, there is a folder hacs-govee-VERSION\custom_components\govee
