### ISSUE TITLE
Different Polling Intervals for Different Devices 

### ISSUE THREAD

**Issue by Neekster** [LaggAt/hacs-govee#32]
It would be great if I could individually set the polling interval for my devices. For example, I use my Glow lamp to trigger Automations, so I want it to poll often. I don't really care if my Modem Smart Plug polls at all though.

**Comment by LaggAt** [comment]
Whats the reason you want this?

Govee promised to provide a single poll for all devices in an upcoming API update. Hope that arrives soon.

**Comment by Neekster** [comment]
I have 30 devices, so I have to keep the polling rate at 35 seconds. There
are some devices that I don't really care about polling, such as the smart
plug on my modem, or the bulbs that I use as a backup (Why poll something
that's literally in the box). There are also some devices that I use more
often, so I would like to have more up-to-date info in HA.

I am hoping that the single poll for all devices comes soon, as I would no
longer have to wait 30+ seconds for things to update. I'll ask them about
it.

**Comment by LaggAt** [comment]
Just got informed that there is an updated api. As I understand, polling device state is now allowed every 10 seconds for each device. This would need some redesign, but I will investigate on #65 here. So I'm closing here.
