### ISSUE TITLE
Color gradient and flashing modes

### ISSUE THREAD

**Issue by minus218** [LaggAt/hacs-govee#36]
Is there any plan to add a color mode for gradient or flashing type modes? I find myself using the Govee app to apply those modes. But, then something gets messed up and I have to reset Home Assistant. I'd rather just not use the Govee app at all.

**Comment by LaggAt** [comment]
There is a long-term plan to dive into BLE, but I'm talking too long about that :) Hope I will find some time to dig deeper soon.
For now, I'm closing here, as this is mentioned in quite some issues.
