### ISSUE TITLE
HA doesn't list integration anymore after update

### ISSUE THREAD

**Issue by AndreWohnsland** [LaggAt/hacs-govee#39]
## Version of the custom_component

- Home Assistant 2021.9.6
- HACS 1.15.2
- hacs-govee 0.2.1

## Describe the bug

After updating to the latest Home Assistant 2021.9.6 the integration did not work any more. After deleting the integration, I wanted to add it again, but it cannot be found at configuration > integration > add integration like described at the readme. Versions are currently the latest available, as stated above. I also tried uninstalling and doing a fresh installation of hacs-govee from HACS, which did not fix the issue.

**Comment by Balake** [comment]
Having same issue

**Comment by proffalken** [comment]
I'm wondering if this is why I can't control my existing device and can't add a new one even though it shows up in the app.

**Comment by BioCryo** [comment]
I updated HA to core-2021.6.0 before all this and I just installed Govee from HACS for the first time (also had issues installing HACS). I couldn't get Govee to show up in configuration>integrations, I had to revert my installation back to the previous version (core-2021.5.0) of HA to see it.

**Comment by AndreWohnsland** [comment]
After the release of the latest Home Assistant OS 6.4, I did an update, and now I can see again the integration. I was able to add it back, and my devices work like expected again. Therefore, I am closing this Issue for now. It seems either a downgrade (like described by @BioCryo) or the update to the latest versions available today seems to resolve the issue.

**Comment by BioCryo** [comment]
@AndreWohnsland I concur, after downgrading, I reinstalled the update and I could still see the integration.
