### ISSUE TITLE
Doesn't work with Govee Dual Smart Plug H5082 - found alternative solution

### ISSUE THREAD

**Issue by bkarpe** [LaggAt/hacs-govee#42]
I couldn't figure out how to get the Govee Dual Smart Plug (H5082) to work with this integration. The solution I found was to install Homekit (following the directions at [https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi) and then use the Homekit Controller integration (see https://www.home-assistant.io/integrations/homekit_controller/). It works flawlessly.

**Comment by LaggAt** [comment]
Hi, 

I don't know about Govee Dual Smart Plug (H5082).
What is ist?

**Comment by Neekster** [comment]
Here's a link:
https://smile.amazon.com/Govee-Bluetooth-Assistant-Remotely-Certified/dp/B095KG3M4Y/

**Comment by youplaymenot** [comment]
@bkarpe  I am super new to home assistant and these are some of the last devices I have to add and I was pulling my hair out. It does appear that the dual smart plugs do not work with the addon, so thank you for your solution.

**Comment by bkarpe** [comment]
The only other caveat is to set your WiFi router to WPA (not WPA2 or WPA3). I discovered this previously, but then I had a power outage that reset my router, and I had to discover this again.

**Comment by youplaymenot** [comment]
@bkarpe Thank you for heads up, it just sucks that it isn't officially supported. It even has Bluetooth in it at as well so things would be all local.

**Comment by austin202220** [comment]
My solution has been to control the Govee Dual Plug H5082 using the Google Assistant SDK which allows you to use them with service calls.

> service: google_assistant_sdk.send_text_command
data:
    command: turn on outlet 1

**Comment by calebsw83** [comment]
> I couldn't figure out how to get the Govee Dual Smart Plug (H5082) to work with this integration. The solution I found was to install Homekit (following the directions at https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Raspberry-Pi and then use the Homekit Controller integration (see https://www.home-assistant.io/integrations/homekit_controller/). It works flawlessly.

Would this require an iOS device? 



> My solution has been to control the Govee Dual Plug H5082 using the Google Assistant SDK which allows you to use them with service calls. https://www.home-assistant.io/integrations/google_assistant_sdk
> 
> > service: google_assistant_sdk.send_text_command
> > data:
> > command: turn on outlet 1

This seems quite convoluted, and I'm working my way through setting this up, but is it really as easy as referring to 'outlet 1' or 'outlet 2' with each device's commands?
