### ISSUE TITLE
Missing features for Govee Lyra (H6072)

### ISSUE THREAD

**Issue by stefanzierpersonal** [LaggAt/hacs-govee#48]
Set up the integration with a Govee Lyra floor lamp - the only thing I can do in HA is turn it on and off. Can't change colors or select presets. Any way to add these features? Happy to write the code myself and submit a PR if you have any pointers.

**Comment by stefanzierpersonal** [comment]
Ah yeah, I can change colors and brightness now. Does the Govee API expose any of the other features also?

**Comment by Neekster** [comment]
No, unfortunately it doesn't. I do wish that Govee would allow API control
over scenes, music modes, and DIYs.
