### ISSUE TITLE
Doesn't work for 

### ISSUE THREAD

**Issue by atv2016** [LaggAt/hacs-govee#49]
**Is your feature request related to a problem? Please describe.**
Doesn't work for:
https://www.amazon.co.uk/gp/product/B07QCMCVD7/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Describe the solution you'd like**
Working status

**Describe alternatives you've considered**

**Additional context**

**Comment by mike2246** [comment]
Doesn't work with the following
https://www.amazon.com/Govee-Purifiers-Bedroom-Google-Assistant/dp/B098XW27YS/ref=sr_1_3?keywords=govee+air+purifier&qid=1641229039&sprefix=govee+air%2Caps%2C103&sr=8-3

https://www.amazon.com/Govee-Humidifiers-Humidifier-Essential-H7142101/dp/B098PWLX4C/ref=sr_1_2_sspa?keywords=govee+humidifier&qid=1641229079&sprefix=govee+hum%2Caps%2C96&sr=8-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExTVg2MFVOSVBMUkRVJmVuY3J5cHRlZElkPUEwMDEwMDM5MjFVM01OU1U0M0tGQSZlbmNyeXB0ZWRBZElkPUExMDEwNjAyMkZPNDVYVE9JUE9QOSZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

Describe the solution you'd like
Working status

Describe alternatives you've considered
On/Off State - Fan Speed

Additional context
Add any other context or screenshots about the feature request here.

**Comment by Neekster** [comment]
Same issue here. It usually takes Govee a couple of weeks to get new
devices into the API. However, I doubt that the fan speed will be
controllable from the API. I'm currently using a workaround that uses IFTTT
and Webhooks. Let me know if you'd like me to send you how I did that.

**Comment by mike2246** [comment]
Yes Please, Thanks!

**Comment by LaggAt** [comment]
Hi, two issues here ...
* I do not own a purifier
* I have no idea if an API exists.
Feel free to investigate and tell me more.

**Comment by Neekster** [comment]
Govee Smart Appliances do not work with the API. Why? I don't know.

And that janky 'solution' that I referenced in a previous comment stopped working after a week, so it's not a viable option for long term use.
