### ISSUE TITLE
Brigthness problem with H6199

### ISSUE THREAD

**Issue by Juffle74** [LaggAt/hacs-govee#50]
Hi,

With the Govee H6199 when I set the light (from within the Govee app or Lovelace) at 1% the brightness value become -17  at 50% it go to 36 and at 100% it go to 89.

The brightness is set correctly but the value returned is wrong and that force Lovelace to show the cursor at a lower level that the light is currently set.

Any idea ?

Thank you

**Comment by LaggAt** [comment]
Try pulling the slider up to max, and down to min once. We have some self learning in place.
If it doesn't help, please provide logs and describe what you did at what log line, and what should happen.

**Comment by Juffle74** [comment]
Sorry for the late reply... It did not work but for some reason after many days it did fix itself.
