### ISSUE TITLE
Integration not appearing

### ISSUE THREAD

**Issue by HitmanDMC** [LaggAt/hacs-govee#51]
Hello,
I installed the latest version from HACS (0.2.1) and I don't see any HA integration named govee in HA. I tried to restart the OS for many times but with the same result. I'm using hassio, version core-2021.11.1 on a rPI 4. I don't have any logs to provide since doesn't seems to throw any error at the installation of the HACS plugin.

**Comment by yannikHASS** [comment]
I got the same issue

**Comment by HitmanDMC** [comment]
I rechecked and now seems to work. Not sure what was the problem. The plugin is the same version.

**Comment by Bazz-Man** [comment]
Same for me, installed via HACS, go to configuration, add integration and Govee is not in the list or if I search for it.

**Comment by Bazz-Man** [comment]
> Same for me, installed via HACS, go to configuration, add integration and Govee is not in the list or if I search for it.

So you need to  “generate” the URL to add this integration:

Click here: [Link to Integrations: Add integration – My Home Assistant 28](https://my.home-assistant.io/redirect/config_flow_start/?domain=govee)

**Comment by RuiChuz** [comment]
> > Same for me, installed via HACS, go to configuration, add integration and Govee is not in the list or if I search for it.
> 
> So you need to “generate” the URL to add this integration:
> 
> Click here: [Link to Integrations: Add integration – My Home Assistant 28](https://my.home-assistant.io/redirect/config_flow_start/?domain=govee)

Thanks a lot. Same problem, now solved

**Comment by SonnyBBQ** [comment]
This happens often for integrations installed via HACS and can usually be solved by deleting browser cache and reloading the page.

**Comment by aliparr-** [comment]
> > Same for me, installed via HACS, go to configuration, add integration and Govee is not in the list or if I search for it.
> 
> So you need to “generate” the URL to add this integration:
> 
> Click here: [Link to Integrations: Add integration – My Home Assistant 28](https://my.home-assistant.io/redirect/config_flow_start/?domain=govee)

I have the same issue as above, but this link didn't solve things for me.

I've successfully added the govee add-on via HACS. It shows in the HACS->Integrations page within my Home Assistant. But if I go to Configuration -> Integrations -> Add Integration and search for govee, it doesn't show up. 
I've restarted HA multiple times, tried clearing my browser cache/used a different browser. It's just not there...

Any idea what to try next? Thanks!

**Comment by nathang21** [comment]
I am also having the same problem.

When clicking the generated link, it acts to setup Govee, I say yes and then get: 
`Error - Config flow could not be loaded`

Logs show:
```
Logger: homeassistant.config_entries
Source: config_entries.py:711
First occurred: 20:45:56 (1 occurrences)
Last logged: 20:45:56

Cannot find integration govee
```

I've cleared browser cache, logged out and back in, and restarted HA multiple times.

**Comment by aliparr-** [comment]
> Edit: Well not sure why, but re-installing the integration from HACS, then restarting, and then trying to add it again worked.

And now for me too! How strange. One thing that I did differently this time was to log out -> log in at each step. So to be specific I:
1) Uninstalled the integration via HACS 
2) Restarted HA
3) Logged out of HA
4) Logged back in to HA
5) Hard refreshed (using Chrome on a Mac)
6) Installed the integration via HACS
7) Restarted HA
8) Logged out of HA
9) Logged back in to HA
10) Hard refreshed (using Chrome on a Mac)
11) Finally it shows up as an Integration

Oddly, I had tried via an incognito window before (requiring a log-in), but that didn't work. Maybe something about the act of logging-out clears some needed cache/cookies? 

Anyway. Please to have this finally working. Thanks for the tip nathang21 !

**Comment by LaggAt** [comment]
Seems original poster has it solved, it's sometimes a hassle. Usually installing with hacs and waiting for some minutes does the trick. Also try clearing browser cache, restarting home assistant.
