### ISSUE TITLE
Creating a new release.

### ISSUE THREAD

**Issue by chriscn** [LaggAt/hacs-govee#55]
Please can you create a new release with the new code regarding attributes? 

I'd also like to discuss the possibility of removing the Govee state entity.

**Edit:** I'd be happy to work on this and help deploy this but would need contributor access.

**Comment by Juffle74** [comment]
Yes...

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 10:05:47 (3 occurrences)
Last logged: 10:05:47

Entity light.aura_right (<class 'custom_components.govee.light.GoveeLightEntity'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.aura_left (<class 'custom_components.govee.light.GoveeLightEntity'>) implements device_state_attributes. Please report it to the custom component author.
Entity light.tv (<class 'custom_components.govee.light.GoveeLightEntity'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by chriscn** [comment]
@Juffle74 this seemingly has been fixed in the latest commit but there isn't anything to suggest that it has been published.
