### ISSUE TITLE
Update failed bad gateway

### ISSUE THREAD

**Issue by raptr55** [LaggAt/hacs-govee#60]
Hello 

Its about few days that i see this erorr in the home assistant log and the entity become unavaible, but not in the govee app. This Is the log:

update failed for xx:xx:xx:xx:xx:xx:xx:xx: API-Error 400: {"message":"Device Not Found","status":400}
update failed for xx:xx:xx:xx:xx:xx:xx:xx: API-Error 502: <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> </body> </html>

And 

error getting state for device GoveeDevice(device='xx:xx:xx:xx:xx:xx:xx:xx', model='H6199', device_name='ambilight tv', controllable=True, retrievable=True, support_cmds=['turn', 'brightness', 'color', 'colorTem'], support_turn=True, support_brightness=True, support_color=True, support_color_tem=True, online=False, power_state=False, brightness=137, color=(217, 225, 255), color_temp=0, timestamp=1646314286.30328, source=<GoveeSource.API: 'api'>, error='API-Error 400: {"message":"Device Not Found","status":400}', lock_set_until=1646261818.676849, lock_get_until=1646261819.676884, learned_set_brightness_max=100, learned_get_brightness_max=100, before_set_brightness_turn_on=False, config_offline_is_off=False): API-Error 400: {"message":"Device Not Found","status":400}

**Comment by joekeslar** [comment]
Same - any updates?

**Comment by LaggAt** [comment]
So it seems it's not related to the implementation here, closing.
