### ISSUE TITLE
H7061 - cannot control individual flood lights

### ISSUE THREAD

**Issue by stefanzierpersonal** [LaggAt/hacs-govee#64]
This is a single controller that can control 2 or 4 individual flood lights. Through the native Govee app, they can be controlled individually (color, brightness), but not through HA. Not sure if this is a limitation of the API, but wondering if there is a path to fixing it.

**Comment by Neekster** [comment]
It's an API limitation. Same applies to the Sconces and Flow Plus/Pro Bars. If you want to CO trol them individually, you'd have to remove the Govee controller and replace it with WLED or something similar.
