### ISSUE TITLE
Govee not found in Integrations after installing with HACS

### ISSUE THREAD

**Issue by mschiff805** [LaggAt/hacs-govee#81]
I have installed the latest version of Govee inside of HACS.  I then restarted HA.

It shows here and everything looks good.
![image](https://user-images.githubusercontent.com/106358907/170614475-de1afc7e-7451-42ca-9ec4-40302a146b9c.png)

I then go to the sidebar, I click Configuration (mine actually says Settings), then Devices & Services, then the + icon, and when I type in Govee, it doesn't find it.

![image](https://user-images.githubusercontent.com/106358907/170615075-41f02825-247c-4ff2-8e32-4d76a0259289.png)

I inserted this in the YAML file under the section I already had under Logger, Logs:
    homeassistant.components.govee: debug
    custom_components.govee: debug
    govee_api_laggat: debug

When I check the full logs, I don't see anything in red, nor do I see anything with govee in the logs.

I am new at this and just learning, so my apologies if I am being lame here.

**Comment by mschiff805** [comment]
Nevermind I figured it out.  I did not have HACS installed correctly.  I changed the username from hassio to my own that I created.  Just learned that it's supposed to stay as hassio.

**Comment by hendrikwedhorn** [comment]
Had the same issue, but i needed to Update Home Assistant from 2022.6.5 -> 2022.6.6. Weird....

**Comment by zyphlar** [comment]
I have a default unchanged VirtualBox install running 2022.8.6 and it's experiencing this issue. I don't see any error logs, it's just as if I did nothing / the integration or custom repository doesn't exist outside of HACS.
