### ISSUE TITLE
Integration Name Change - s/Govee LED Strips/Govee/

### ISSUE THREAD

**Issue by dutchie027** [LaggAt/hacs-govee#9]
Currently the integration is called "Govee LED Strips" however as already shown/proven in the forum(s) and I can also confirm, the H5081 plug works, so maybe a better name for the Integration is simply "Govee" as it does more than LED strips...

**Comment by LaggAt** [comment]
Hm ... if I google H5081 i find pictures of a baking oven 👍 
Didn't expect that.

The name wasn't choosen wisely. I started with "hey, let's see what we can do" then typing some code.

If I think of it, 'led strips' isn't the best choice. Govee alone would mean supporting their temp and security devices, and all the bluetooth things, which we do not support.

I think I'll leave that open for discussion for a while.

**Comment by dutchie027** [comment]
I was excited when I saw the excerpt that said Bluetooth things for a second (I have a few of them) 😄  

As for the full name, I’m not sure that people would assume it means everything, but I also see where you’re coming from. If I look at every other integration though, iRobot for example, it doesn’t support all iRobot devices...Philips Hue, it doesn’t support the Philips Hue Wiz, so I’m not so sure just “Govee” isn’t the right name.

**Comment by LaggAt** [comment]
There is also https://community.home-assistant.io/t/govee-ble-thermometer-hygrometer-sensor/166696
At least we should distinct from that?

"Govee lights"?

**Comment by dutchie027** [comment]
Maybe Govee WiFi?

**Comment by dutchie027** [comment]
Interestingly enough too, the WiFi plug (which is why I don't suggest "lights" in the name) is [H5081 per their documentation](https://m.media-amazon.com/images/I/91lG9XqYQSL.pdf). Maybe someone with a baking oven uses their plug? :)

**Comment by LaggAt** [comment]
After some time of re-thinking I'll just go with "Govee".
The integration description clearly shows it is for lights, and this opens future use for more govee products if someone wants to add these.
