### ISSUE TITLE
Can't add integration from integration screen

### ISSUE THREAD

**Issue by savy10** [LaggAt/hacs-govee#96]
Following the instructions, I've added the Govee integration through HACS, however, after 5 minutes or so of the following message "Please wait, starting configuration wizard for Govee" I then get this "Config flow could not be loaded: Unknown error".

![image](https://user-images.githubusercontent.com/33453442/199375310-586a2456-6047-488b-a13e-4be63d181b3a.png)

![image](https://user-images.githubusercontent.com/33453442/199375273-c1fb825b-79b9-4497-b083-79a45a23b624.png)

**Comment by tjkcc** [comment]
Same trouble

**Comment by raelix** [comment]
same for me

**Comment by raelix** [comment]
you can just change:
- the ```light.py``` line 8 to ```from govee_api_laggat.govee_api_laggat import GoveeError```
- the ```config_flow.py``` line 6 to ```from govee_api_laggat.govee_api_laggat import GoveeError```
After the changes restart home assistant

**Comment by tjkcc** [comment]
> 

worked, thank you @raelix

**Comment by savy10** [comment]
@raelix thank you. It actually updated itself shortly after and fixed itself! Appreciate you letting me know another solution though.

Cheers
